### PR TITLE
solved mrcll

### PR DESCRIPTION
**Pull request by remrcll**

### CODE REVIEW

**Comment by Ungoot** [comment]
`border-collapse: separate;` does nothing, why did you use that?

**Comment by Ungoot** [comment]
Now it does not look like the mock-up.

**Comment by remrcll** [comment]
> Now it does not look like the mock-up.

Somebody removed the mockup, so I don't know how it should look like.

**Comment by Ungoot** [comment]
Yea I think it was me, I was trying to fix something else. I'm on it, give me a minute.

**Comment by Ungoot** [comment]
Mockup is back online

**Comment by Ungoot** [comment]
In your css;

On line 2 you define a solid border and on line 3 you change it to groove, if you want to use groove you can just define it on line 2. Also groove does not really work with black. It needs 2 colors to have that 3d effect and one of the colors is by default black. If you define the other color black too it just looks like a solid line.

In this example the line should be solid so if you just delete line 3 it would be done.

**Pull request merged**
