### PR TITLE
solved

### PR DESCRIPTION
**Pull request by vinc86**

### CODE REVIEW

**Comment by Ungoot** [comment]
Your page does not look like the mockup. Please make it so.
Your links do not open in new tabs.

**Comment by Ungoot** [comment]
Still does not look like the mock-up.

**Comment by vinc86** [comment]
i wanted to perzonalize a little bit :D

Il giorno lun 27 apr 2020 alle ore 14:33 Bleda <notifications@github.com>
ha scritto:

**Comment by Ungoot** [comment]
Yes, it looks good but the mock-up is there so you learn to work with them. One of the aims of the exercise is to make it look like the mock-up.

**Comment by vinc86** [comment]
Allright, i'm going to Fix it

Il Lun 27 Apr 2020, 14:51 Bleda <notifications@github.com> ha scritto:

**Comment by Ungoot** [comment]
Thank you, Merged.

**Pull request merged**
